config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :journeys, only: %i[index show] do
    resources :challenges, only: %i[edit update]
  end
  resources :users, only: %i[edit update]
  resources :rewards, only: %i[show index]
  resources :profiles, only: %i[show edit update]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(profile_params)
      redirect_to profile_path, notice: "Your profile was updated"
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :username, :photo, :career)
  end
end

app/views/profiles/_form.html.erb
<%= simple_form_for(user, url: profile_path, method: :patch, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :username %>
    <%= f.input :photo, as: :file %>
  </div>

  <div>
    <%= f.button :submit, 'Update Profile', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
<%= link_to 'Back', profile_path, class: "back-btn" %>
  <div class="card">
    <h2>Edit profile</h2>

    <%= render 'form', user: @user %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <%= link_to 'Back', journeys_path, class: "back-btn mt-4" %>
  <div class="row justify-content-center rounded-5 p-4 col-lg-5 col-md-6 col-sm-8 mx-auto" style="background-color: #b0b9db;">
    <h2><%= "#{current_user.first_name} #{current_user.last_name}" %></h2>
    <div class="my-3 mx-auto">
      <%= cl_image_tag @user.photo.key, class: "avatar-large d-block mx-auto"  %>
    </div>
    <p><strong>Username:</strong> <%= "#{current_user.username}" %> </p>
    <p><strong>Email:</strong> <%= "#{current_user.email}" %> </p>
    <p><strong>Career:</strong> <%= "#{current_user.career}" %> </p>
    <%= link_to 'Edit Profile', edit_profile_path, class: "btn" %>
  </div>
</div>