config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :journeys, only: %i[index show] do
    resources :challenges, only: %i[edit update]
  end
  resources :users, only: %i[edit update]
  resources :rewards, only: %i[show index]
  resources :profiles, only: %i[show edit update]
end

app/models/journey.rb
class Journey < ApplicationRecord
  has_many :challenges, dependent: :destroy
  belongs_to :user
  belongs_to :reward
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  def index
    @journeys = current_user.journeys
  end

  def show
    @journey = Journey.find(params[:id])
    @challenges = @journey.challenges if @journey
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Journey not found."
    redirect_to journeys_path
  end
end

app/views/journeys/index.html.erb
<div class="container my-5">
  <div>
    <h1 class="main-header">Welcome!</h1>
    <h3 class="text-center">Here are your daily challenges.</h3>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @journeys.each do |journey| %>
    <!-- Modal -->
    <div class="modal fade" id="<%= dom_id(journey) %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content card-border">
          <div class="model-header d-flex justify-content-end mt-3 mx-3">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center">
            <h2 class="mb-3"><%= journey.title %></h2>
          <div class="challenges">
            <% journey.challenges.each do |challenge| %>
            <div class="challenge">
              <%= render partial: 'challenges/challenge', locals: { journey: journey, challenge: challenge } %>
            </div>
            <% end %>
            <div>
              <% completed = journey.challenges.select { |challenge| challenge.completed == true } %>
              <%= link_to 'Reward', reward_path(journey.reward), class: "btn-reward mt-6 mb-6 reward_journey_#{ journey.id } #{ 'd-none' unless journey.challenges.length == completed.length }" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
      <div class="col-6 col-md-4 col-lg-2">
        <div class="journey-card <%= 'journey-card-not-completed' if journey.challenges.length != completed.length%>">
          <div class="journey-card-inner">
            <div class="journey-card-front <%= 'completed-card journey-card-inner-gradient' if journey.challenges.length == completed.length %>" data-bs-toggle="modal" data-bs-target="#<%= dom_id(journey) %>">
              <img class='journey-image' src="https://res.cloudinary.com/dl1yqlzar/image/upload/v1701888523/The_Journey__7_-removebg-preview_yq9xwd.png" >
              <% if journey.challenges.length == completed.length %>
                <div class="completed-status">
                  <p class="mb-0 fs-5 text-center">Completed</p>
                </div>
              <% end %>
              <div class="journey-image <%=journey.challenges.length == completed.length ? "background-image-card-linear" : "background-image-card" %>"> </div>
              <div class="journey-card-title">
                <%= journey.title %>
              </div>
            </div>
            <div class="journey-card-back">
              <div class="journey-details">
                <h4 class= "card-another mb-3 mt-4 fs-5">Today's challenges</h4>
                <div class="journey-challenges">
                  <button type="button" class="btn mt-6" data-bs-toggle="modal" data-bs-target="#<%= dom_id(journey) %>">Start</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var cards = document.querySelectorAll(".journey-card");
    cards.forEach(function (card) {
      card.addEventListener("click", function () {
          card.classList.toggle("is-flipped");
      });
    });
  });
</script>

app/views/journeys/show.html.erb
<div class="card text-white mx-auto col-lg-4 col-md-6 col-sm-4">
  <h2 class="mb-4"><strong>Let's go!</strong></h2>
  <div class="challenges" data-controller="challenges">
    <% @journey.challenges.each do |challenge| %>
    <div class="challenge">
      <%= render partial: 'challenges/challenge', locals: { journey: @journey, challenge: challenge } %>
    </div>
    <% end %>
    <div class="mx-auto">
      <% completed = @journey.challenges.select { |challenge| challenge.completed == true } %>
      <% if @journey.challenges.length == completed.length%>
        <%= link_to 'Reward', reward_path(3), class: 'reward-btn btn btn-info mt-4' %>
      <% end %>
    </div>
  </div>
</div>